name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - name: Install capnp
        run: |
          cd /tmp &&
          curl -O https://capnproto.org/capnproto-c++-1.0.2.tar.gz &&
          tar zxf capnproto-c++-1.0.2.tar.gz &&
          cd capnproto-c++-1.0.2 &&
          ./configure &&
          make -j8 &&
          sudo make install &&
          rm -rf capnproto-c++-1.0.2.tar.gz capnproto-c++-1.0.2
      - run: pnpm install
      - run: pnpm lint
      - run: pnpm test:gen
      - run: pnpm test:types
      - run: pnpm build
      - run: pnpm vitest --coverage
      - uses: codecov/codecov-action@v4
